name: Build
on: 
  push:
    branches: 
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Linting and TypeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - run: npm run lint-ci
        if: ${{ always() }}
      - run: npm run typecheck
        if: ${{ always() }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Pages
        id: pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5          
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npm run sync-deps
      - run: npm run build
        env:
          BASE_URL: ${{ steps.pages.outputs.base_url }}
      - uses: actions/upload-artifact@v4
        with: 
          name: website
          path: dist/
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        if: github.ref == 'refs/heads/main'
        with: 
          path: dist/
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

    